# <span style="color:darkblue"> Lecture 8: Local/Global and Apply </span>

<font size = "5">

In the previous lecture we ...

- Worked through the definition of functions
- Illustrated some examples

In this lecture, we will ...

- Discuss the syntax of functions (local/global)
- Apply functions to multiple elements in a data frame
- Introduce ".py" files

## <span style="color:darkblue"> I. Import Libraries </span>

In [1]:
# the "pandas" library is for manipualting datasets

import pandas as pd
import numpy as np

## <span style="color:darkblue"> II. Local/Global Variables </span>

<font size="5"> 

Most of the variables we've defined so far are "global"

- Stored in working environment
- Can be referenced in other parts of the notebook

<font size = "5">
Example:

In [2]:
message_hello = "hello"
number3       = 3

In [3]:
print(message_hello + " world")
print(number3 * 2)

hello world
6

<font size = "5">

Any "global" variable can be referenced inside functions

- However, this can lead to mistakes
- Preferrably, include **all** the inputs as parameters

<font size = "5">

$f(x,y,z) = x + y + z$

In [4]:
# Correct Example:
def fn_add_recommended(x,y,z):
    return(x + y + z)

print(fn_add_recommended(x = 1, y = 2, z = 5))
print(fn_add_recommended(x = 1, y = 2, z = 10))

8
13

In [5]:
# Example that runs (but not recommended)
# Python will try to fill in any missing inputs
# with variables in the working environment
def fn_add_notrecommended(x,y):
    return(x + y + z)

z = 5
print(fn_add_notrecommended(x = 1, y = 2))
z = 10
print(fn_add_notrecommended(x = 1, y = 2))

8
13

<font size ="5">

Variables defined inside functions are "local"

- Stored "temporarily" while running
- Includes: Parameters + Intermediate variables

<font size = "5">

Local variables supercede global variables

In [7]:
# This is an example where we define a quadratic function
# (x,y) are both local variables of the function
# 
# When we call the function, only the arguments matter.
# any intermediate value inside the function

def fn_square(x):
    y = x**2
    return(y)

x = 5
y = -5

print(fn_square(x = 1))

print(x)
print(y)

1
5
-5

<font size = "5">

Local variables are **not** stored in the working environment

In [16]:
# The following code assigns a global variable x
# Inside the function

x = 5
y = 4

print("Example 1:")
print(fn_square(x = 10))    #local variable x = 10
print(x)
print(y)

print("Example 2:")
print(fn_square(x = 20))
print(x)
print(y)

Example 1:
100
5
4
Example 2:
400
5
4

<font size = "5">

To permanently modify a variable, use the "global" command

In [17]:
def modify_x():
    global x
    x = x + 5

x = 1
# Now, running the function wil permanently increase x by 5.
modify_x()
print(x)

6

In [12]:
modify_x()
print(x)

11

<font size = "5">

Try it yourself:

- What happens if we run "modify_x" twice?
- What happens if we add "global y" inside "fn_square"?

In [13]:
# Write your own code here

modify_x()

## <span style="color:darkblue"> III. Operations over data frames (apply/map) </span>

<font size = "5">

Create an empty data frame

In [18]:
data  = pd.DataFrame()  # create empty data frame

In [19]:
print(data)

Empty DataFrame
Columns: []
Index: []

<font size = "5">

Add variables

In [20]:
# The following are lists with values for different individuals
# "age" is the number of years
# "num_underage_siblings" is the total number of underage siblings
# "num_adult_siblings" is the total number of adult siblings

data["age"] = [18,29,15,32,6]
data["num_underage_siblings"] = [0,0,1,1,0]
data["num_adult_siblings"] = [1,0,0,1,0]

In [23]:
data

   age  num_underage_siblings  num_adult_siblings
0   18                      0                   1
1   29                      0                   0
2   15                      1                   0
3   32                      1                   1
4    6                      0                   0

<font size = "5">

Define functions

In [21]:
# The first two functions return True/False depending on age constraints
# The third function returns the sum of two numbers
# The fourt function returns a string with the age bracket

fn_iseligible_vote = lambda age: age >= 18

fn_istwenties = lambda age: (age >= 20) & (age < 30)

fn_sum = lambda x,y: x + y

def fn_agebracket(age):
    if (age >= 18):
        status = "Adult"
    elif (age >= 10) & (age < 18):
        status = "Adolescent"
    else:
        status = "Child"
    return(status)

<font size = "5">
Applying functions with one argument: <br>

```python
 apply(myfunction)
 ```
 - Takes a dataframe series (a column vector) as an input
 - Computes function separately for each individual

In [23]:
# The fucntion "apply" will extract each element and return the function value
# It is similar to running a "for-loop" over each element

data["can_vote"]    = data["age"].apply(fn_iseligible_vote)
data["in_twenties"] = data["age"].apply(fn_istwenties)
data["age_bracket"] = data["age"].apply(fn_agebracket)


# NOTE: The following code also works:
# data["can_vote"]    = data["age"].apply(lambda age: age >= 18)
# data["in_twenties"] = data["age"].apply(lambda age: (age >= 20) & (age < 30))

display(data)

,age,num_underage_siblings,num_adult_siblings,can_vote,in_twenties,age_bracket
0,18,0,1,True,False,Adult
1,29,0,0,True,True,Adult
2,15,1,0,False,False,Adolescent
3,32,1,1,True,False,Adult
4,6,0,0,False,False,Child

<font size = "5">

Creating a new variable

In [24]:
# adds a new column called new_var which tells us if age >=18
data['new_var'] = data['age'].apply(lambda age: age >= 18)
data

,age,num_underage_siblings,num_adult_siblings,can_vote,in_twenties,age_bracket,new_var
0,18,0,1,True,False,Adult,True
1,29,0,0,True,True,Adult,True
2,15,1,0,False,False,Adolescent,False
3,32,1,1,True,False,Adult,True
4,6,0,0,False,False,Child,False

<font size = "5">

Dropping an existing variable

In [25]:
data = data.drop(columns=['new_var'])
data

,age,num_underage_siblings,num_adult_siblings,can_vote,in_twenties,age_bracket
0,18,0,1,True,False,Adult
1,29,0,0,True,True,Adult
2,15,1,0,False,False,Adolescent
3,32,1,1,True,False,Adult
4,6,0,0,False,False,Child

<font size = "5">

Mapping functions with one or more arguments <br>

**Definition:** The ```map()``` function executes a <br>
specified function for each item in an iterable <br>
(such as a list or an array). <br>
 The item is sent to the function as a parameter.

```python
list(map(myfunction, list1,list2, ....))
```

In [26]:
list(map(fn_iseligible_vote, data["age"]))

[True, True, False, True, False]

In [27]:
# Repeat the above example with map
# We use list() to convert the output to a list
# The first argument of map() is a function
# The following arguments are the subarguments of the function

data["can_vote_map"] = list(map(fn_iseligible_vote, data["age"]))

In [28]:
# In this example, there are more than two arguments

data["num_siblings"] = list(map(fn_sum,
                                data["num_underage_siblings"],
                                data["num_adult_siblings"]))

In [29]:
list(map(fn_sum, data["num_underage_siblings"],
         data["num_adult_siblings"]))

[1, 0, 1, 2, 0]

In [30]:
data["num_underage_siblings"] + data["num_adult_siblings"]

0    1
1    0
2    1
3    2
4    0
dtype: int64

In [31]:
data["num_underage_siblings"]

0    0
1    0
2    1
3    1
4    0
Name: num_underage_siblings, dtype: int64

In [32]:
data["num_adult_siblings"]

0    1
1    0
2    0
3    1
4    0
Name: num_adult_siblings, dtype: int64

<font size = "5">

<span style="color:darkgreen"> Recommended! </span>

- Arguments can be split into multiple lines!
- Start a separate line after a comma
- Experts recommend each line has 80 characters or less

In [33]:
data["num_siblings"] = list(map(fn_sum,
                                data["num_underage_siblings"],
                                data["num_adult_siblings"]))

<font size = "5">

Try it yourself!

- Write a function checking whether num_siblings $\ge$ 1
- Add a variable to the dataset called "has_siblings"
- Assign True/False to this variable using "apply()"

In [38]:
# Write your own code

try_yourself = pd.DataFrame(data)

def check_siblings(x):
    return x >= 1

try_yourself["has_siblings"] = try_yourself["num_siblings"].apply(check_siblings)

print(try_yourself)

   age  num_underage_siblings  num_adult_siblings  can_vote  in_twenties  \
0   18                      0                   1      True        False
1   29                      0                   0      True         True
2   15                      1                   0     False        False
3   32                      1                   1      True        False
4    6                      0                   0     False        False

  age_bracket  can_vote_map  num_siblings  has_siblings
0       Adult          True             1          True
1       Adult          True             0         False
2  Adolescent         False             1          True
3       Adult          True             2          True
4       Child         False             0         False

<font size = "5">

Try it yourself!

- Read the car dataset "data_raw/features.csv"
- Create a function that tests whether mpg $\ge$ 29
- Add a variable "mpg_above_29" which is True/False if mpg $\ge$ 29
- Store the new dataset to "data_clean/features.csv"

In [40]:
# Write your own code

car_data = pd.read_csv('data_raw/features.csv')

print(car_data)

def mpg_above_29(x):
    if x>=29:
        status = ("True")
    else:
        status = ("False")
    return status

# Add a new column to dataset (True/False for mpg>=29)
car_data['mpg_above_29'] = car_data['mpg'].apply(mpg_above_29)

# Store the new column data
car_data.to_csv("data_clean/features.csv")

#print the new data set that you just newly defined
car_data

FileNotFoundError: [Errno 2] No such file or directory: 'data_raw/features.csv'

<font size = "5">

Try it yourself!

- Map can also be applied to simple lists!
- Create a lambda function with arguments {fruit,color}.
- The function returns the string <br>
" A {fruit} is {color}"
- Create the following two lists:

``` list_fruits  = ["banana","strawberry","kiwi"] ```

``` list_colors  = ["yellow","red","green"] ```
- Use the list(map()) function to output a list with the form

In [41]:
# Write your own code

list_fruits = ["banana", "strawberry", "kiwi"]
list_colors = ["yellow", "red", "green"] 

new_list = list(map(lambda fruit, color: f"A {fruit} is {color}",
         list_fruits,
         list_colors))

print (new_list)

['A banana is yellow', 'A strawberry is red', 'A kiwi is green']

## <span style="color:darkblue"> IV. (Optional) External Scripts </span>

<font size = "5">

".ipynb" files ...

- Markdown + python code
- Great for interactive output!

".py" files ...

- Python (only) script
- Used for specific tasks
- Why? Split code into smaller, more manageable files


<font size = "5">

<table><tr>
<td style = "border:0px"> <img src="figures/screenshot_py_functions.png" alt="drawing" width="300"/>  </td>
<td style = "border:0px">

File with functions

 </td>
</tr></table>

**A module is just a Python program that ends with <br>
.py extension and a folder that contains a <br>
 module becomes a package!**

<font size = "5">

We can import functions into the working <br>
environment from a file

In [ ]:

import scripts.example_functions as ef

<font size = "5">

We reference them using the alias

In [ ]:
x = 1
print(ef.fn_quadratic(1))
print(ef.fn_quadratic(5))

ef.message_hello("Juan")

1
25

'hi Juan'


<font size = "5">

<table><tr>
<td style = "border:0px"> <img src="figures/screenshot_py_variables.png" alt="drawing" width="300"/>  </td>
<td style = "border:0px">

File with variables

- Storing values/settings
- Variables are global <br>
(can be referenced later)

</td>
</tr></table>

<font size = "5">

We can also import and reference variables

In [ ]:
import scripts.example_variables as ev

In [ ]:
# When we run this program
# # the value of alpha will be overwritten

alpha = 1
print(alpha)
print(ev.alpha)

1
5

<font size = "5">

We can also use ``` from ``` and ``` * ``` <br>
to import variables directly into the working <br>
environment

In [ ]:
from scripts.example_variables import *

print(alpha)
print(beta)
print(gamma)
print(delta)

5
10
20
100