# <span style="color:darkblue"> QTM 151 - Quiz 3 </span>

## Try to submit as an HTML file

<font size="5"> 

Print your name below

In [1]:
# Write your answer here

print("Christina Dai")

Christina Dai

<font size = "5" >
This quiz is open book 

- You can use the lecture notes
- You will get partial credit for attempting the questions
- To get full credit, the code should run as intended
- You should <span style="color:red"> NOT </span> communicate with other students

Print the following message: <br>

"I will abide by Emory's code of conduct"

In [2]:
# Write your answer here:

print("I will abide by Emory's code of conduct")

I will abide by Emory's code of conduct

<font size = "5">

Import the libraries "numpy" and "pandas"

In [3]:
# Write your answer here

import numpy as np
import pandas as pd


<font size = "5">

(a) Replace the values of a column

<font size = "3">

- Import the "data_raw/constructors.csv" file
- Replace the values "British", "Japanese", and "Irish" with <br>
"UK", "Japan", "Ireland" in the column "nationality"


HINT: See the example in Lecture 12

In [5]:
# Write your own code

constructors = pd.read_csv("data_raw/constructors.csv")

constructors["nationality"] = constructors["nationality"].replace("British","UK")
constructors["nationality"] = constructors["nationality"].replace("Japanese","Japan")
constructors["nationality"] = constructors["nationality"].replace("Irish","Ireland")

<font size = "5">

(b) Aggregate and query

<font size = "3">

- Import the "data_raw/sprint_results.csv" file
- Subset the observations for 'constructorId == 3' using ```.query()```
- Obtain the maximum of "laps" by "driverId" <br> 
 using ``` .groupby().agg() ```
- Subset the drivers with a maximum of laps $\ge 10$
- Store the results of all these operations in a dataframe <br>
```sprint_results_agg ```

In [12]:
# Write your own code

sprint_results = pd.read_csv("data_raw/sprint_results.csv")

sprint_agg = (sprint_results.query("constructorId == 3")
                         .groupby('driverId')
                         .agg(max_laps = ('laps','max')))

sprint_result_agg1 = sprint_agg.sort_values(by = "max_laps", ascending = False)
sprint_result_agg1

sprint_result_agg=sprint_result_agg1.iloc[0:5]
sprint_result_agg

          max_laps
driverId
847             24
849             24
848             23

<font size = "5">

(c) Recode a numeric colum

<font size = "3">

- Import the "data_raw/races.csv" file
- Recode the "year" column into a new column "year_brackets" <br>
with the following categories

$\qquad$ ``` ["1950-1965","1966-1980","1980-onwards"] ```

$\qquad$ HINT: Use the "pd.cut()" command.

In [6]:
# Write your own code

races = pd.read_csv("data_raw/races.csv")

bins_year=[1950,1965,1980,float('inf')] 
labels_year=["1950-1965",
             "1966-1980",
             "1980-onwards"]

races['year_brackets']=pd.cut(races['year'],
                                bins=bins_year,
                                right=True,
                                labels=labels_year)
races

,raceId,year,round,circuitId,name,date,time,url,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time,year_brackets
0,1,2009,1,1,Australian Grand Prix,2009-03-29,06:00:00,http://en.wikipedia.org/wiki/2009_Australian_G...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N,1980-onwards
1,2,2009,2,2,Malaysian Grand Prix,2009-04-05,09:00:00,http://en.wikipedia.org/wiki/2009_Malaysian_Gr...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N,1980-onwards
2,3,2009,3,17,Chinese Grand Prix,2009-04-19,07:00:00,http://en.wikipedia.org/wiki/2009_Chinese_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N,1980-onwards
3,4,2009,4,3,Bahrain Grand Prix,2009-04-26,12:00:00,http://en.wikipedia.org/wiki/2009_Bahrain_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N,1980-onwards
4,5,2009,5,4,Spanish Grand Prix,2009-05-10,12:00:00,http://en.wikipedia.org/wiki/2009_Spanish_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N,1980-onwards
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1097,1116,2023,19,69,United States Grand Prix,2023-10-22,19:00:00,https://en.wikipedia.org/wiki/2023_United_Stat...,2023-10-20,17:30:00,2023-10-21,18:00:00,\N,\N,2023-10-20,21:00:00,2023-10-21,22:00:00,1980-onwards
1098,1117,2023,20,32,Mexico City Grand Prix,2023-10-29,20:00:00,https://en.wikipedia.org/wiki/2023_Mexico_City...,2023-10-27,18:30:00,2023-10-27,22:00:00,2023-10-28,17:30:00,2023-10-28,21:00:00,\N,\N,1980-onwards
1099,1118,2023,21,18,São Paulo Grand Prix,2023-11-05,17:00:00,https://en.wikipedia.org/wiki/2023_S%C3%A3o_Pa...,2023-11-03,14:30:00,2023-11-04,14:30:00,\N,\N,2023-11-03,18:00:00,2023-11-04,18:30:00,1980-onwards
1100,1119,2023,22,80,Las Vegas Grand Prix,2023-11-19,06:00:00,https://en.wikipedia.org/wiki/2023_Las_Vegas_G...,2023-11-17,04:30:00,2023-11-17,08:00:00,2023-11-18,04:30:00,2023-11-18,08:00:00,\N,\N,1980-onwards
1101,1120,2023,23,24,Abu Dhabi Grand Prix,2023-11-26,13:00:00,https://en.wikipedia.org/wiki/2023_Abu_Dhabi_G...,2023-11-24,09:30:00,2023-11-24,13:00:00,2023-11-25,10:30:00,2023-11-25,14:00:00,\N,\N,1980-onwards

<font size = "5">

(d) Aggregate and sort

<font size = "3">

- Import the "data_raw/sprint_results.csv" file
- Obtain the maximum of "laps" by "driverId" <br> 
using ``` .groupby().agg() ```
- Sort the teams in descending order using of <br>
the maximum of laps using ``` .sort_values() ```

In [9]:
# Write your own code

sprint_results = pd.read_csv("data_raw/sprint_results.csv")

sorted_sprints = (sprint_results.groupby('driverId')
                        .agg(max_laps = ('laps','max'))
                        .sort_values("max_laps",ascending = False))
sorted_sprints

          max_laps
driverId
1               24
4               24
854             24
853             24
852             24
849             24
847             24
846             24
844             24
842             24
841             24
840             24
839             24
832             24
830             24
825             24
822             24
817             24
815             24
20              24
8               24
855             24
848             23
9               18

<font size = "5">

(e) Rename column

<font size = "3">

- Import the "data_raw/sprint_results.csv" file
- Rename the column "time" to "time_unformatted"

HINT: Create a dictionary and use ```.rename(columns = ...)``` <br>
See Lecture 15

In [21]:
# Write your own code

sprint_results = pd.read_csv("data_raw/sprint_results.csv")

dict_rename_sprint_results = {"time": "time_unformatted"}
sprint_renamed = sprint_results.rename(columns = dict_rename_sprint_results)

<font size = "5">

(f) Merge dataset

<font size = "3">

- Import the "data_raw/sprint_results.csv" and <br>
"data_raw/constructors.csv" files
- Create a new dataset with  ```pd.merge()``` using <br>
"sprint_results" as the primary dataset, and <br>
"constructors" as the secondary dataset, merging on <br>
the column "constructorId"
- To get full points **ONLY** merge the "nationality" column <br>
from the secondary dataset (not all the columns)

HINT: Use ```[[...]]``` to extract a subset of columns <br>
from the secondary dataset before merging, including the <br>
"constructorId" column

In [20]:
# Write your own code

sprint_results = pd.read_csv("data_raw/sprint_results.csv")
constructors = pd.read_csv("data_raw/constructors.csv")

sprint_constructors_merge = pd.merge(sprint_results,
                        constructors[["constructorId","nationality"]],
                         on = "constructorId",
                         how = "left")